export enum ProjectScope {
    ADDITION = 'ADDITION',
    INTERIOR_BUILD_OUT = 'INTERIOR_BUILD_OUT',
    NEW_BUILD = 'NEW_BUILD',
    RENOVATION = 'RENOVATION',
    TENANT_FIT_OUT = 'TENANT_FIT_OUT'
}