export enum ProjectScope {
    ADDITION = 'ADDITION',
    INTERIOR_BUILD_OUT = 'INTERIOR BUILD OUT',
    NEW_BUILD = 'NEW BUILD',
    RENOVATION = 'RENOVATION',
    TENANT_FIT_OUT = 'TENANT FIT OUT'
}